name: FaceTrackCam
options:
  bundleIdPrefix: com.anmol
targets:
  FaceTrackCam:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: . # Adjust if your source files are in a specific subfolder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.anmol.FaceTrackCam
      INFOPLIST_FILE: Info.plist # Change or add if you use a custom plist path
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
